# yaml-language-server: $schema=https://render.com/schema/render.yaml.json
services:
  - type: web
    name: stormskud
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    numInstances: 1
    autoDeployTrigger: "off"
